# Generated by Django 3.2.6 on 2021-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="title",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
