# Generated by Django 3.2.6 on 2021-08-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_test_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
    ]
