# Generated by Django 3.2.6 on 2021-08-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_auto_20210812_2124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choice",
            field=models.ManyToManyField(
                related_name="question",
                through="tests.ChoiceItem",
                to="tests.Choice",
            ),
        ),
    ]
