# Generated by Django 3.2.6 on 2021-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_alter_question_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="max_points",
        ),
        migrations.AddField(
            model_name="answer",
            name="points",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="test",
            name="max_points",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
